//
// Created by Johannes Martin on 14.09.21.
//

#ifndef FORESTTEX4TREE_TIKZGENERATOR_H
#define FORESTTEX4TREE_TIKZGENERATOR_H

#include <iostream>
#include <fstream>
#include <string>
#include <regex>
#include <random>

#include "Constants.h"
#include "TreeNode.h"

class TikzGenerator {
public:
    TikzGenerator(const std::string &file);
    ~TikzGenerator();

    void createBoxes(TreeNode *t, bool randomizeParticlePosition=false);
    void treeBoxes2tikz(TreeNode *t);
    void drawParticles(TreeNode *t, bool randomizeParticlePosition=false);

private:
    std::ofstream ofs;

    const std::string header { "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n"
                               "%%%%% Generated by forestTex4tree %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n"
                               "%%%%% https://github.com/jammartin/forestTex4tree %%%%%%%%%%%%%%%%%%%%%%%%%\n"
                               "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n"
    };
    const std::string particlePattern { R"RAW(([0-9]+),?.*)RAW" };

    const double margin { DOMAINSIZE/25. };
};


#endif //FORESTTEX4TREE_TIKZGENERATOR_H
